#! /usr/bin/env bash
# vim: filetype=sh syntax=sh

if [[ $# -gt 0 ]]
then
  while (($#))
  do
    if [[ -e "$1" ]]
    then
      xattr -cr "$1"
    fi

    shift
  done
else
  echo 'No files specified'
fi

